In [1]:
import torch

Define the parameters:

In [3]:
w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

The function forward makes the prediction:

In [6]:
def forward(x):
    yhat = w * x + b
    return yhat

In [7]:
x = torch.tensor([[1.0]])
yhat = forward(x)
yhat

tensor([[1.]], grad_fn=<ThAddBackward>)

In [8]:
x=torch.tensor([[1.0],[2.0]])

In [9]:
x.shape

torch.Size([2, 1])

Make prediction

In [12]:
yhat = forward(x)
yhat

tensor([[1.],
        [3.]], grad_fn=<ThAddBackward>)

Cast the following nested list to a tensor and make a prediction:

In [13]:
x = torch.tensor([[1.0], [2.0], [3.0]])
yhat = forward(x)
yhat

tensor([[1.],
        [3.],
        [5.]], grad_fn=<ThAddBackward>)

### Class Linear ¶

The linear class can be used to make a prediction. You'll also use the linear class to build more complex models. Import the module:

In [14]:
from torch.nn import Linear
import torch

Set the random seed because the parameters are randomly initialized:

In [15]:
torch.manual_seed(1)

Create the object by using the constructor:

In [16]:
lr = Linear(in_features = 1, out_features = 1, bias = True)

Review the model parameters:

In [17]:
print(list(lr.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


Make a single prediction:

In [18]:
x = torch.tensor([[1.0]])
yhat = lr(x)
yhat

tensor([[0.0739]], grad_fn=<ThAddmmBackward>)

It's just like using the function forward:

In [19]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
yhat

tensor([[0.0739],
        [0.5891]], grad_fn=<ThAddmmBackward>)

In [20]:
x = torch.tensor([[1.0], [2.0], [3.0]])
yhat = lr(x)
yhat

tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<ThAddmmBackward>)

### Build Custom Modules 

Now, let's build a custom module. You can make more complex models by using this method later on.

In [21]:
from torch import nn

Define the class:

In [23]:
class LR(nn.Module):
    def __init__(self, input_size,output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self, x):
        out = self.linear(x)
        return out

Create an object by using the constructor:

In [24]:
lr = LR(1, 1)

Review the model parameters:

In [25]:
print(list(lr.parameters()))

[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [26]:
lr.linear

Linear(in_features=1, out_features=1, bias=True)

Make single or multiple predictions:

In [29]:
x = torch.tensor([[1.0]])
yhat = lr(x)
yhat

tensor([[0.2755]], grad_fn=<ThAddmmBackward>)

In [30]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
yhat

tensor([[0.2755],
        [0.0816]], grad_fn=<ThAddmmBackward>)

In [31]:
x = torch.tensor([[1.0], [2.0], [3.0]])
lr1 = LR(1, 1)
yhat = lr(x)
yhat

tensor([[ 0.2755],
        [ 0.0816],
        [-0.1122]], grad_fn=<ThAddmmBackward>)